### ISSUE TITLE
landscapetools 0.5

### ISSUE THREAD

**Issue by marcosci** [ropensci/landscapetools#14]
Tasks to streamline **landscapetools** for future updates:

- [x] Remove font related code/files
- [x] Write tests for everything
- [x] Write more detailed documentation
- [x] Vignettes for the homepage
- [x] Get rid of dependencies: viridis, rastervis, purrr, cowplot, magrittr, checkmate, extrafont

... in light of future updates:

1. Do we want to stick to the current naming scheme?
2. If anything bugs you here - feel free to discuss.

**Comment by mhesselbarth** [comment]
Currently, basically all funcitions have the prefix `util_` no matter if they are e.g. for visualization or to convert data, right? I think it would make sense, to come up with a bit more detailed nameing scheme similar to `landscapemetrics`.

**Comment by Nowosad** [comment]
Talking about the **landscapetools**, is that expected behavior? 

``` r
library(landscapetools)
l1 <- NLMR::nlm_fbm(64, 64)
l2 <- NLMR::nlm_planargradient(64, 64)
l3 <- NLMR::nlm_randomrectangularcluster(ncol = 60, nrow = 60, minl = 5, maxl = 10)
l4 <- NLMR::nlm_random(64, 64)

lst1 <- list(layer1 = l1,
             layer2 = l2,
             layer3 = l3,
             layer4 = l4)
util_facetplot(lst1, div_scales = FALSE)
```

![](https://i.imgur.com/xOYOrLo.png)

``` r
util_facetplot(lst1, div_scales = TRUE)
```

![](https://i.imgur.com/uj1eoaV.png)

<sup>Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by marcosci** [comment]
Sure, do we want to keep show as prefix for the visualisation functions? Any ideas for merge, classify, rescale? :thinking: I think util could stay for raster2tibble for example, or?

And Jakub this was pretty much WIP :laughing: I think util_facetplot will either way end up in util_plot as method and the idea with div_scales was to have a seperate color scale for each facet - to show spatial variables like pH, land use, ... at the moment the coloring works fine, but cowplot has to be replaced with grid.

**Comment by mhesselbarth** [comment]
For `util_classify()` I would suggest something as `get_classes()`  or `get_discrete()` if we want to somehow stick to the naming style of `landscapemetrics`. As said before, all plot functions would get the `show_`-prefix. For the rest, I actually like the `util_`-prefix (e.g. `util_merge()` and `util_rescale()`).

**Comment by marcosci** [comment]
Perfect, will do that :) 
`show_landscapes` is roughly done, needs a bit of tweaking still.

**Comment by marcosci** [comment]
Just found this, may be helpful for `show_landscapes`: https://github.com/clauswilke/relayer

**Comment by marcosci** [comment]
util_writeESRI needs to be a bit faster, have to check how writeRaster makes that in raster.

**Comment by marcosci** [comment]
So, both of you now also have write access here.

I condensed it down to 6 dependencies, fonts are gone etc. and it should be ready for the merge with landscapemetrics :+1:

**Comment by mhesselbarth** [comment]
Wait... did we decide to merge the two? Or do you mean to move some functions from landscapemetrics here?

**Comment by marcosci** [comment]
Move the get functions and vis stuff, or? 😅

**Comment by Nowosad** [comment]
@marcosci Would it be possible (and desired) to remove one or two more dependencies?

``` r
# devtools::install_github("jimhester/itdepends")
library(dplyr)
library(itdepends)

lst_dep = dep_usage_pkg("landscapetools")

lst_dep %>%
    group_by(pkg) %>% 
    count(sort = TRUE)
#> # A tibble: 9 x 2
#> # Groups:   pkg [9]
#>   pkg                n
#>   <chr>          <int>
#> 1 base             408
#> 2 ggplot2          154
#> 3 raster            40
#> 4 landscapetools    15
#> 5 grid               4
#> 6 dplyr              3
#> 7 tibble             3
#> 8 classInt           1
#> 9 tidyr              1
```

<sup>Created on 2019-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by marcosci** [comment]
You mean dplyr. tibble or tidyr? 
Sure, I can try that :-)
If we find an c++ implementation of the fisher algorithm, we could also get rid of classint.

**Comment by marcosci** [comment]
Down to:

```
Imports: 
    classInt,
    ggplot2,
    raster,
    tibble
```

**Comment by Nowosad** [comment]
Impressive!

**Comment by marcosci** [comment]
classInt can be taken of the list by implementing:

https://github.com/macroevolution/bammtools/blob/master/BAMMtools/src/jenksBrks.c

**Comment by marcosci** [comment]
all done, if there is anything you would like to see before the _merger_ let me know!
