### ISSUE TITLE
Issues with `show_landscape()` for categorical rasters

### ISSUE THREAD

**Issue by Nowosad** [ropensci/landscapetools#18]
Today, I started working on https://github.com/ropensci/landscapetools/issues/17. 
My first step is to make the new functions in the same fashion as existing ones, however I've got some issues with plotting a categorical raster:

``` r
library(landscapemetrics)
library(landscapetools)
library(raster)
#> Loading required package: sp
data("podlasie_ccilc")
podlasie_ccilc2 = as.factor(podlasie_ccilc)
```

```r
# error 1
show_landscape(podlasie_ccilc, discrete = TRUE)
#> Error: Continuous value supplied to discrete scale
```
``` r

# error 2
show_landscape(podlasie_ccilc2, discrete = TRUE)
#> Error in names(x) <- value: 'names' attribute [1] must be the same length as the vector [0]
```

<sup>Created on 2019-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by marcosci** [comment]
I fixed the first issue, but the second one is a bug/feature coming from raster:

```r
test <- raster::raster(matrix(1:100, 10, 10))
test2 <-  as.factor(test)
raster::as.data.frame(test2, xy = TRUE)
```

... if you think this is unwanted behaviour in raster we could file an issue there, if not we could try to get rid of the factor in the plotting function.

**Comment by Nowosad** [comment]
It's perfect now, @marcosci. The second example was rather an idea to escape the first error than a proper solution.

**Comment by marcosci** [comment]
Perfect :-) Do you plan to commit something soon? Otherwise, I will update the CRAN version soonish, because the current version causes some problems in NLMR and landscapemetrics.

**Comment by Nowosad** [comment]
Feel free to update the CRAN version. I will definitely commit something, but cannot tell exactly when.
