### ISSUE TITLE
Re-add continuous integration workflows?

### ISSUE THREAD

**Issue by maelle** [ropensci/landscapetools#38]
:wave: here! It seems there's no CI for this repo?

I see you used to use tic. tic now supports GitHub Actions (or to use GitHub Actions directly see https://usethis.r-lib.org/reference/github_actions.html)

**Comment by bitbacchus** [comment]
We use appveyor and travis ci and at least travis should still work (afaik). On the other hand, GH actions is very convenient and it is 5 mins to switch. What do you say, @marcosci?

**Comment by maelle** [comment]
For info regarding Travis CI: https://ropensci.org/blog/2020/11/19/moving-away-travis/

**Comment by mhesselbarth** [comment]
I added a pull request (#40) adding GitHub actions CI. Probably needs some fine-tuning once accepted and merged.

**Comment by mhesselbarth** [comment]
[![R-CMD-check](https://github.com/ropensci/landscapetools/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/ropensci/landscapetools/actions/workflows/R-CMD-check.yaml)
Everything seems to work now (I just pushed a few tiny documentation fixes)

**Comment by bitbacchus** [comment]
> [![R-CMD-check](https://github.com/ropensci/landscapetools/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/ropensci/landscapetools/actions/workflows/R-CMD-check.yaml) Everything seems to work now (I just pushed a few tiny documentation fixes)

me, too ;-)
