### ISSUE TITLE
random % with corresponding % from real landscape 

### ISSUE THREAD

**Issue by wegmann** [ropensci/landscapetools#6]
Dear authors of landscapetools,

thanks a lot, the package looks great. 

Just an idea: if the percentage for the random class landscape can be picked automatically from a real classification then these two landscapes could be compared. Additionally "constraints" for the random landscape could be added, e.g. no landscape on masked areas such as water. This would allow to test for driving factors of landscape arrangement.

the r.pi.nlm command in the r.pi suit within GRASS GIS is doing similar stuff, maybe interesting to look at it:
https://grass.osgeo.org/grass74/manuals/addons/r.pi.html

**Comment by marcosci** [comment]
Hi Martin :-)

Makes perfect sense, will have a look at that in the next days (grass is most likely a never-ending resource of inspiration for us). Thanks for the comment!

I have for a couple of weeks now an email draft in my inbox - is there a way to see your grass algorithms for the midpoint displacement somewhere (from your dissertation)? didn't find it in grass anymore.

**Comment by wegmann** [comment]
Hi Marco,

I moved in the past years more and more to R hence I neglected GRASS a 
bit, but try to get back into it. Therefore I am not anymore up-to-date 
with the GRASS code status.

What do you mean with "midpoint displacement"? In which command was it 
used?


regards, Martin

**Comment by marcosci** [comment]
r.nlm was I think the algorithm you mentioned in your thesis :)

**Comment by wegmann** [comment]
Hi Marco,

r.nlm was renamed to r.pi.nlm, and r.pi.nlm.stats (and old trial 
r.pi.nlm.circ)

https://grass.osgeo.org/grass74/manuals/addons/r.pi.nlm.html

https://grass.osgeo.org/grass74/manuals/addons/r.pi.nlm.stats.html

the code can be seen here:

https://trac.osgeo.org/grass/browser/grass-addons/grass7/raster/r.pi/r.pi.nlm.stats


regards, Martin

**Comment by marcosci** [comment]
Ah, very nice :+1: thanks a lot - would it be OK with you (if time allows it) if I implement it in [nlmr](https://github.com/ropensci/nlmr)? and sorry for sidetracking you here :)

**Comment by wegmann** [comment]
of course, please feel free to implement the whole r.pi suit into your R 
package!

**Comment by mattfrit** [comment]
Hi Martin,

I finally found some time to implement your idea... :)

You can now give an optional 'real' landscape to the util_classify function. The classification then overwrites the weightings with the proportions from this landscape. In case you want to mask parts of the nlm landscape you have to give the exact value for the class in the real landscape. There is an example in the help file.

I hope this covers your idea/request, if not feel free to reopen this issue or make another nice suggestion to improve our package.

Thanks and kind regards
Matthias

**Comment by wegmann** [comment]
Hi Matthias,

great, thanks a lot. I will test is asap.

regards, Martin
